language: go
sudo: false
go:
- "1.10.x"
addons:
  apt:
    packages:
      - libpcre++-dev
      - libpcre2-dev
#before_install:
#  - sudo apt-get install libpcre++-dev
before_script:
  - go vet ./...
script:
 - go test -v ./...
