sudo: true
dist: trusty
language: go
go:
- "1.10.x"
install:
  - sudo apt-get --yes install snapd
  - sudo snap install libpcre++-dev
#before_install:
#  - sudo apt-get install libpcre++-dev
before_script:
  - go vet ./...
script:
 - "gofmt -s -d $(find . -type f -name '*.go') |& perl -pe 'END{exit($. > 0 ? 1 : 0)}'"
 - go test -v ./...
